name: Build Windows App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Windows Executable
      run: npx electron-builder --win --x64 --publish never

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Financial-Automation-App
        path: dist/*.exe
