name: Build Windows App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Windows App
        run: npx electron-builder --win

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Installer
          path: dist/*.exe
